/**
 * @file visualizer.c
 * @brief An SDL application to visualize planetary orbit data from a CSV file.
 *
 * This program reads a 3D data file generated by the kepler_sim_3d tool
 * and displays a simple, animated top-down view of the solar system with
 * persistent orbital trails.
 *
 * Use the mouse wheel to zoom in and out.
 * Click the mouse button to pause/resume the animation.
 * Use the UP/DOWN arrow keys to change the animation speed.
 * Use the LEFT/RIGHT arrow keys to change the playback direction.
 *
 * Compilation:
 * gcc visualizer.c -o sdl_visualizer `sdl2-config --cflags --libs` -lSDL2_ttf -lm
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <math.h>

#define MAX_PLANETS 10
#define MAX_LINE_LEN 1024
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
#define PIXELS_PER_AU 100.0 // At 1x zoom, 1 AU = 100 pixels
#define MAX_TRAIL_LENGTH 500 // Draw the last 500 segments of the trail
#define VERSION "v1.1"

// Struct to hold a single frame of data for all planets
struct Frame {
    char date[11];
    double x[MAX_PLANETS];
    double y[MAX_PLANETS];
};

int main(int argc, char *argv[]) {
    char input_filename[100];
    struct Frame *frames = NULL;
    int frame_count = 0;
    char *planet_names[MAX_PLANETS];
    int num_planets = 0;
    int earth_idx = -1, moon_idx = -1; // Indices for Earth and Moon

    printf("--- SDL Solar System Visualizer ---\n");
    printf("Enter Input CSV Filename (e.g., data_3d.csv): ");
    if (scanf("%99s", input_filename) != 1) {
        fprintf(stderr, "Invalid input.\n");
        return 1;
    }

    // --- Load Data File into Memory ---
    FILE *infile = fopen(input_filename, "r");
    if (infile == NULL) {
        perror("Error opening input file");
        return 1;
    }

    char line[MAX_LINE_LEN];
    // Read header and find Earth/Moon indices
    if (fgets(line, sizeof(line), infile)) {
        line[strcspn(line, "\n")] = 0;
        char *token = strtok(line, ","); // Skip "Date"
        while ((token = strtok(NULL, ",")) != NULL && num_planets < MAX_PLANETS) {
            char *p_name = strdup(token);
            *strchr(p_name, '_') = '\0';
            if (strcmp(p_name, "Earth") == 0) earth_idx = num_planets;
            if (strcmp(p_name, "Moon") == 0) moon_idx = num_planets;
            planet_names[num_planets++] = p_name;
            strtok(NULL, ","); strtok(NULL, ","); // Skip _y and _z
        }
    }

    // Read data frames
    while (fgets(line, sizeof(line), infile)) {
        frames = realloc(frames, (frame_count + 1) * sizeof(struct Frame));
        char *line_ptr = line;
        
        char *token = strsep(&line_ptr, ",");
        strncpy(frames[frame_count].date, token, 10);
        frames[frame_count].date[10] = '\0';

        for (int i = 0; i < num_planets; i++) {
            frames[frame_count].x[i] = atof(strsep(&line_ptr, ","));
            frames[frame_count].y[i] = atof(strsep(&line_ptr, ","));
            strsep(&line_ptr, ","); // Skip Z
        }
        frame_count++;
    }
    fclose(infile);
    printf("Loaded %d days of data.\n", frame_count);

    // --- Initialize SDL ---
    if (SDL_Init(SDL_INIT_VIDEO) < 0) {
        fprintf(stderr, "Could not initialize SDL: %s\n", SDL_GetError());
        return 1;
    }
    if (TTF_Init() == -1) {
        fprintf(stderr, "Could not initialize SDL_ttf: %s\n", TTF_GetError());
        return 1;
    }

    SDL_Window *window = SDL_CreateWindow("Solar System Visualizer",
                                          SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
                                          SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_SHOWN);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
    TTF_Font *font = TTF_OpenFont("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14);
    if (!font) {
        fprintf(stderr, "Failed to load font: %s\n", TTF_GetError());
        font = TTF_OpenFont("/usr/share/fonts/corefonts/arial.ttf", 14);
        if (!font) {
             fprintf(stderr, "Failed to load fallback font. Text will not be rendered.\n");
        }
    }

    // --- Main Loop ---
    int running = 1;
    int is_paused = 0;
    int current_frame = 0;
    double zoom_level = 1.0;
    int frame_increment = 1;
    int direction = 1;
    SDL_Event e;

    while (running) {
        // --- Event Handling ---
        while (SDL_PollEvent(&e) != 0) {
            if (e.type == SDL_QUIT) {
                running = 0;
            } else if (e.type == SDL_MOUSEWHEEL) {
                if (e.wheel.y > 0) zoom_level *= 1.2; else zoom_level /= 1.2;
                if (zoom_level < 0.01) zoom_level = 0.01;
                if (zoom_level > 200.0) zoom_level = 200.0;
            } else if (e.type == SDL_MOUSEBUTTONDOWN) {
                if (is_paused && (current_frame >= frame_count - 1 || current_frame <= 0)) {
                    current_frame = (direction == 1) ? 0 : frame_count - 1;
                }
                is_paused = !is_paused;
            } else if (e.type == SDL_KEYDOWN) {
                switch(e.key.keysym.sym) {
                    case SDLK_UP:
                        frame_increment++; if (frame_increment > 100) frame_increment = 100;
                        break;
                    case SDLK_DOWN:
                        frame_increment--; if (frame_increment < 1) frame_increment = 1;
                        break;
                    case SDLK_LEFT: direction = -1; break;
                    case SDLK_RIGHT: direction = 1; break;
                }
            }
        }

        // --- Drawing ---
        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_RenderClear(renderer);

        // --- Draw Trails ---
        int trail_start = current_frame - MAX_TRAIL_LENGTH;
        if (trail_start < 1) trail_start = 1;

        for (int i = trail_start; i <= current_frame; i++) {
            double earth_x_trail = (earth_idx != -1) ? frames[i].x[earth_idx] : 0;
            double earth_y_trail = (earth_idx != -1) ? frames[i].y[earth_idx] : 0;
            double prev_earth_x_trail = (earth_idx != -1) ? frames[i-1].x[earth_idx] : 0;
            double prev_earth_y_trail = (earth_idx != -1) ? frames[i-1].y[earth_idx] : 0;

            for (int p = 0; p < num_planets; p++) {
                double x1 = frames[i - 1].x[p];
                double y1 = frames[i - 1].y[p];
                double x2 = frames[i].x[p];
                double y2 = frames[i].y[p];

                if (p == moon_idx && earth_idx != -1) {
                    x1 += prev_earth_x_trail; y1 += prev_earth_y_trail;
                    x2 += earth_x_trail; y2 += earth_y_trail;
                }
                
                double sx1 = SCREEN_WIDTH / 2 + (x1 * PIXELS_PER_AU * zoom_level);
                double sy1 = SCREEN_HEIGHT / 2 + (y1 * PIXELS_PER_AU * zoom_level);
                double sx2 = SCREEN_WIDTH / 2 + (x2 * PIXELS_PER_AU * zoom_level);
                double sy2 = SCREEN_HEIGHT / 2 + (y2 * PIXELS_PER_AU * zoom_level);
                
                SDL_SetRenderDrawColor(renderer, 50, 50, 50, 255);
                SDL_RenderDrawLine(renderer, (int)sx1, (int)sy1, (int)sx2, (int)sy2);
            }
        }
        
        // Draw Sun
        SDL_SetRenderDrawColor(renderer, 255, 255, 0, 255);
        SDL_Rect sun_rect = {SCREEN_WIDTH / 2 - 5, SCREEN_HEIGHT / 2 - 5, 10, 10};
        SDL_RenderFillRect(renderer, &sun_rect);

        // Draw Planets (the "live" dots)
        double earth_x_now = (earth_idx != -1) ? frames[current_frame].x[earth_idx] : 0;
        double earth_y_now = (earth_idx != -1) ? frames[current_frame].y[earth_idx] : 0;

        for (int i = 0; i < num_planets; i++) {
            double planet_x = frames[current_frame].x[i];
            double planet_y = frames[current_frame].y[i];

            if (i == moon_idx && earth_idx != -1) {
                planet_x += earth_x_now;
                planet_y += earth_y_now;
            }

            double screen_x = SCREEN_WIDTH / 2 + (planet_x * PIXELS_PER_AU * zoom_level);
            double screen_y = SCREEN_HEIGHT / 2 + (planet_y * PIXELS_PER_AU * zoom_level);

            SDL_SetRenderDrawColor(renderer, 200, 200, 200, 255);
            SDL_Rect planet_rect = {(int)screen_x - 2, (int)screen_y - 2, 5, 5};
            SDL_RenderFillRect(renderer, &planet_rect);

            if(font) {
                SDL_Color white = {255, 255, 255, 255};
                SDL_Surface* text_surface = TTF_RenderText_Solid(font, planet_names[i], white);
                SDL_Texture* text_texture = SDL_CreateTextureFromSurface(renderer, text_surface);
                SDL_Rect text_rect = {(int)screen_x + 5, (int)screen_y - 5, text_surface->w, text_surface->h};
                SDL_RenderCopy(renderer, text_texture, NULL, &text_rect);
                SDL_FreeSurface(text_surface);
                SDL_DestroyTexture(text_texture);
            }
        }
        
        // Render Info Text
        if(font) {
            SDL_Color white = {255, 255, 255, 255};
            char info_text[120], status_text[20] = "";

            if (is_paused && (current_frame >= frame_count - 1 || current_frame <= 0)) {
                snprintf(status_text, sizeof(status_text), "[ENDED]");
            } else if (is_paused) {
                snprintf(status_text, sizeof(status_text), "[PAUSED]");
            }

            snprintf(info_text, sizeof(info_text), "Date: %s | Zoom: %.1fx | Speed: %dx (%s) %s | %s", 
                     frames[current_frame].date, zoom_level, frame_increment, 
                     direction == 1 ? "FWD" : "REV", status_text, VERSION);
            SDL_Surface* info_surface = TTF_RenderText_Solid(font, info_text, white);
            SDL_Texture* info_texture = SDL_CreateTextureFromSurface(renderer, info_surface);
            SDL_Rect info_rect = {10, 10, info_surface->w, info_surface->h};
            SDL_RenderCopy(renderer, info_texture, NULL, &info_rect);
            SDL_FreeSurface(info_surface);
            SDL_DestroyTexture(info_texture);
        }

        SDL_RenderPresent(renderer);

        // --- Update ---
        if (!is_paused) {
            current_frame += (frame_increment * direction);
            if (current_frame >= frame_count) {
                current_frame = frame_count - 1;
                is_paused = 1;
            }
            if (current_frame < 0) {
                current_frame = 0;
                is_paused = 1;
            }
        }
        SDL_Delay(50);
    }

    // --- Cleanup ---
    if (font) TTF_CloseFont(font);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    TTF_Quit();
    SDL_Quit();
    
    for (int i = 0; i < num_planets; i++) free(planet_names[i]);
    free(frames);

    return 0;
}
