/**
 * @file alignment_finder.c
 * @brief A command-line tool to analyze a CSV file of planetary data and
 * find conjunctions (alignments).
 *
 * This program reads a CSV file generated by the planetary_logger, prompts
 * the user for an alignment threshold (in degrees), and then reports all
 * dates where two or more celestial bodies are within that threshold.
 *
 * Compilation:
 * gcc alignment_finder.c -o alignment_finder -lm
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_PLANETS 20
#define MAX_LINE_LEN 1024

int main(void) {
    char input_filename[100];
    double threshold;

    printf("--- Planetary Alignment Finder ---\n");
    printf("This tool will analyze a CSV file to find conjunctions.\n");
    printf("Enter Input CSV Filename (e.g., data.csv): ");
    scanf("%99s", input_filename);
    printf("Enter Alignment Threshold in Degrees (e.g., 2.0): ");
    scanf("%lf", &threshold);

    FILE *infile = fopen(input_filename, "r");
    if (infile == NULL) {
        perror("Error opening input file");
        return 1;
    }

    char line[MAX_LINE_LEN];
    char *planet_names[MAX_PLANETS];
    int num_planets = 0;

    // --- Read Header Line ---
    if (fgets(line, sizeof(line), infile)) {
        // Remove newline character
        line[strcspn(line, "\n")] = 0;
        
        char *token = strtok(line, ","); // Skip "Date"
        token = strtok(NULL, ",");
        while (token != NULL && num_planets < MAX_PLANETS) {
            planet_names[num_planets] = strdup(token);
            num_planets++;
            token = strtok(NULL, ",");
        }
    } else {
        fprintf(stderr, "Could not read header from file.\n");
        fclose(infile);
        return 1;
    }

    printf("\n--- Found Conjunctions (Threshold: %.2f degrees) ---\n", threshold);

    // --- Read Data Lines ---
    while (fgets(line, sizeof(line), infile)) {
        line[strcspn(line, "\n")] = 0;
        
        char *line_copy = strdup(line); // strtok modifies the string, so we use a copy
        
        char *date_str = strtok(line_copy, ",");
        if (date_str == NULL) {
            free(line_copy);
            continue;
        }

        double longitudes[MAX_PLANETS];
        int planet_idx = 0;
        char *token = strtok(NULL, ",");
        while (token != NULL && planet_idx < num_planets) {
            longitudes[planet_idx] = atof(token);
            planet_idx++;
            token = strtok(NULL, ",");
        }

        // --- Compare all planets to each other for this date ---
        for (int i = 0; i < num_planets; i++) {
            for (int j = i + 1; j < num_planets; j++) {
                double angle_diff = fabs(longitudes[i] - longitudes[j]);
                // Handle the wrap-around case (e.g., 359 degrees and 1 degree)
                if (angle_diff > 180) {
                    angle_diff = 360.0 - angle_diff;
                }

                if (angle_diff <= threshold) {
                    printf("%s: %s and %s are in conjunction (%.2f° apart).\n",
                           date_str, planet_names[i], planet_names[j], angle_diff);
                }
            }
        }
        
        free(line_copy);
    }

    printf("--- Analysis Complete ---\n");

    // --- Cleanup ---
    for (int i = 0; i < num_planets; i++) {
        free(planet_names[i]);
    }
    fclose(infile);

    return 0;
}
